#!/usr/bin/env bash
# This script displays the content of /etc/passwd using while loop and IFS

while IFS=: read -r username password userid groupid userdesc homedir shell; do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell."
    echo "User $userid's place is protected by the passcode $password."
    echo "More info about the user here: USER ID INFO"
    echo
done < /etc/passwd
