#!/usr/bin/env bash
# This script displays the groups visitors by IP and HTTP status code, and displays this data

awk '{ ip[$1][$9]++ } END { for (i in ip) { for (j in ip[i]) { print ip[i][j], i, j } } }' access.log | sort -nr
