#!/usr/bin/env bash
#bash script that creates pid file, prints infinite message, kill resistant
file=/var/run/myscript.pid 
echo $$ >> $file
trap 'echo I hate the kill command; sudo rm $file; exit' SIGTERM
trap 'echo Y U no love me?!' SIGINT
trap 'sudo rm $file; exit' SIGQUIT
while ((1)); do
    echo "To infinity and beyond"
    sleep 2
done
10. #!/usr/bin/env bash
#bash script to manage 'manage_my_process'
if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    pkill -f ./manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "$1" == "restart" ]; then
    pkill -f ./manage_my_process
    sudo rm /var/run/my_process.pid
    ./manage_my_process &
    echo $$ > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
:x

