#!/bin/bash
case "$1" in
    start)
        if [ -f /var/run/my_process.pid ]; then
            echo "manage_my_process is already running."
        else
            nohup bash ./manage_my_process >> /tmp/my_process &
            echo $! > /var/run/my_process.pid
            echo "manage_my_process started."
        fi
        ;;
    stop)
        if [ -f /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
            echo "manage_my_process stopped."
        else
            echo "manage_my_process is not running."
        fi
        ;;
    restart)
        if [ -f /var/run/my_process.pid ]; then
            kill $(cat /var/run/my_process.pid)
            rm /var/run/my_process.pid
        fi
        nohup bash ./manage_my_process >> /tmp/my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted."
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
